# Generated by Django 5.1.2 on 2024-11-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrobjtype',
            name='desc',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание'),
        ),
    ]
